---
title: "R Notebook"
output: html_notebook
---

```{r}
if (!require("tidyr")) {
  install.packages("tidyr", repos="http://cran.rstudio.com/") 
  library(tidyr)
}

```



1.RESHAPE DATA (tidyr pACKAGE)
======================================
##1.Gather
Gather moves column names into a key column, gathering the column values into a single value column.
```{r}
#Using "table4a" from base library ()
#Prior
table4a
```
s

```{r}

tidy.ex1<-gather(table4a,"1999","2000",key = "fecha",value = "nacimientos")
tidy.ex1
```

##2.Spread
Spread moves the unique values of a key column into the column names, spreading the values of a value column across the new columns.
Example1:
```{r}
#Watch before
table2
```


```{r}
#now aply the function
tidy.ex2<-spread(table2, type, count)
tidy.ex2
```

###1.babynames
```{r}
#import a dataset called "babynames"
if (!require("babynames")) {
  install.packages("babynames", repos="http://cran.rstudio.com/") 
  library(babynames)
}

  babynames %>%
  filter(name %in% c("Sue", "Robin", "Leslie")) %>%
  group_by(name, sex) %>%
  summarise(total = sum(n)) 
```
###2. Spread
```{r}
  babynames %>%
  filter(name %in% c("Sue", "Robin", "Leslie")) %>%
  group_by(name, sex) %>%
  summarise(total = sum(n)) %>%
  spread(key = sex, value = total, fill=0)
```
