---
title: "R Notebook"
output: html_notebook
---
```{r}
library(stringr)

```


#1. EXTRACT patterns
```{r}
  #Now we are going to use a "sentences" from "stringr" library
  stringr::sentences
  length(sentences)
  head(sentences)
  #I flip the order of the second and third words
  sentences%>%
          str_replace("([^ ]+) ([^ ]+) ([^ ]+)", "\\1 \\3 \\2")%>%
          head(5)
```

##1. Extracts before a character 


```{r}
library(stringr)
shopping_list <- c("service s4", "loan for school", "loan for university", "Service s2")
```

###1.before a hyphen
```{r}
#Extracts characters 

v2<-str_extract('Abcs-Ddd', "[^-]+")
```


##2. Extracts after, before space

```{r}

str_extract(shopping_list, "[a-z]+")

(?<=\\s) checks whether there is whitespace before
(?=\\s) checks whether there is a whitespace after
(.*) extracts everything in between the white spaces
```


##3. Extracts only numbers
```{r}
str_extract(shopping_list, "\\d")
  
```

##3 Extracts characters in position:  from the first to four 

```{r}
str_extract(shopping_list, "[a-z]{1,4}")
```

##3.extr characters that start with b in position:  from the first to four 

```{r}

str_extract(shopping_list, "\\b[a-z]{1,4}\\b")
```

##Ext dates 
```{r}

#Extract dates with this pattern "18/09/20" 
# datos_ingreso=c("Recuento: 1 Ultimo: 17/12/19 10")

 str_extract(datos_ingreso, "[0-9]{2}/[0-9]{2}/[0-9]{2}")
# 


```



# REMOVE
##Removing vowels
```{r}

var4 <- c("1551.55", "two tables", "a cloud")

#first  
str_remove(var4, "[aeiou]")

#all
str_remove_all(var4, "[aeiou]")

```


##Removing first character 
```{r}

str_remove(var4, ".")
```
##Removing dot (.)
```{r}
gsub("\\.", "", var4, perl=TRUE)
```


