---
title: "R Notebook"
output: html_notebook
---
```{r}
library(stringr)

```



```{r}
  #Now we are going to use a "sentences" from "stringr" library
  stringr::sentences
  length(sentences)
  head(sentences)
  #I flip the order of the second and third words
  sentences%>%
          str_replace("([^ ]+) ([^ ]+) ([^ ]+)", "\\1 \\3 \\2")%>%
          head(5)
```

##3.extract characters before hyphen
```{r}
library(stringr)

v2<-str_extract('Abcs-Ddd', "[^-]+")
```



```{r}
shopping_list <- c("apples x4", "bag of flour", "bag of sugar", "milk x2")
```


##3.extract characters before any special character or space

```{r}

str_extract(shopping_list, "[a-z]+")

```

##3.extract only numbers
```{r}
str_extract(shopping_list, "\\d")
  
```

##3.extract characters in position:  from the first to four 

```{r}
str_extract(shopping_list, "[a-z]{1,4}")
```

##3.extract characters that start with b in position:  from the first to four 

```{r}

str_extract(shopping_list, "\\b[a-z]{1,4}\\b")
```
#Extract dates 
```{r}

#Extract dates with this pattern "18/09/20" 
# datos_ingreso=c("Recuento: 1 Ultimo: 17/12/19 10")

 str_extract(datos_ingreso, "[0-9]{2}/[0-9]{2}/[0-9]{2}")
# 


```


