---
title: "R Notebook"
output: html_notebook
---


```{r}

if (!require("stringr")) {
  install.packages("stringr", repos="http://cran.rstudio.com/") 
  library(stringr)
}


if (!require("tibble")) {
  install.packages("tibble", repos="http://cran.rstudio.com/") 
  library(tibble)
}
if (!require("zoo")) {
  install.packages("zoo", repos="http://cran.rstudio.com/") 
  library(zoo)
}


if (!require("dplyr")) {
  install.packages("dplyr", repos="http://cran.rstudio.com/") 
  library(dplyr)
}

if (!require("readxl")) {
  install.packages("readxl", repos="http://cran.rstudio.com/") 
  library(readxl)
}

if (!require("tidyr")) {
  install.packages("tidyr", repos="http://cran.rstudio.com/") 
  library(tidyr)
}

if (!require("scales")) {
  install.packages("scales", repos="http://cran.rstudio.com/") 
  library(scales)
}


if (!require("visdat")) {
  install.packages("visdat", repos="http://cran.rstudio.com/") 
  library(visdat)
}
if (!require("writexl")) {
  install.packages("writexl", repos="http://cran.rstudio.com/") 
  library(writexl)
}


```



```{r}
#load
app.mant<-read_xlsx("C:/R-Source/5.Daily/Aplicaciones_en_mantenimiento.xlsx",sheet = "Hoja1")

app.herra.estim<-read_xlsx("C:/R-Source/5.Daily/Aplicaciones_herra_estima.xlsx",sheet = "Hoja1")
```


```{r}

app.herra.estim$mante<-0
#Compare
app.herra.estim$mante<-ifelse(match(app.herra.estim$Aplicaciones,app.mant$SIGLAS),"si","no")

app.herra.estim[mante==NA,]
          

```

```{r write}


```

